cookie:
  expiry_days: 30
  key: ndbvgehweyuw8dfbsn # Must be a string
  name: gdgAuthCookie
credentials:
  usernames:
    dkadev:
      email: dev.keshwani345@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Dev Keshwani
      password: dkadev123@
      roles:
      - admin
      - editor
      - viewer

